language: node_js
node_js: 15

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: test
      before_script:
        - cd packages/api
      script:
        - npm run test
    - stage: test
      node_js: 15
      before_install:
        - cd packages/client
      script:
        - npm run test:unit
    - stage: test
      before_install:
        - cd packages/client
      script:
        - npm run test:e2e
branches:
  only:
    - master
    - development
    - refactor/52-refactor-client-code-to-use-store