language: node_js
node_js: 15

jobs:
  include:
    - stage: test
      before_cache:
        - cd packages/api
      script:
        - npm run test
    - stage: test
      before_cache:
        - cd packages/client
      script:
        - npm run test:unit
branches:
  only:
    - master
    - development
    - refactor/52-refactor-client-code-to-use-store