language: node_js
node_js: 15

cache:
  directories:
    - packages/client/node_modules/
    - packages/api/node_modules/

jobs:
  include:
    - stage: test
      before_install:
        - cd packages/api
      script:
        - npm run test
    - stage: test
      before_install:
        - cd packages/client
      script:
        - npm run test:unit
branches:
  only:
    - master
    - development
    - refactor/52-refactor-client-code-to-use-store