language: node_js
node_js: 15
cache: npm

jobs:
  include:
    - stage: test
      before_script:
        - cd packages/api
      script:
        - npm run test
    - stage: test
      node_js: 15
      before_install:
        - cd packages/client
      script:
        - npm run test:unit
branches:
  only:
    - master
    - development
    - refactor/52-refactor-client-code-to-use-store