version: 2.1
on:
  pull_request:
    branches: [ development ]
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm install
          path: packages/client
      - run:
          name: Run tests
          command: npm run test
          path: packages/client