name: Integration Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  test-master-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
        working-directory: packages/client
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
          working-directory: packages/client