name: Backend Continuous Integration

on: [push]

jobs:
  test-development-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
        working-directory: packages/client
      - name: Run Tests
        run: npm run test
        working-directory: packages/client