name: Vault Unit Tests

on:
  pull_request:
    branches: [ development ]

jobs:
  vault-test-development-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install Dependencies
        run: npm ci
        working-directory: packages/vault
      - name: Run Tests
        run: npm run test
        working-directory: packages/vault
